### ISSUE TITLE
Mod Title?

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Gambling#10]
This issue thread should be used for suggesting and discussing mod titles. Current suggestions: 

1. Gambling

2. Fallout 4 Gambling 

3. Commonwealth Gambling 

4. Gambling of the Commonwealth

5. Gambling in the Commonwealth

6. Barstool Games

**Comment by Scrivener07** [comment]
My personal favorite is simply "Gambling". I feel like it is short and descriptive. May second favorite is "Barstool Games". That one is good because it widens the scope of the project beyond betting games. There may be non betting games we want to do that are just fun with no need to wager a bet.

**Comment by Scrivener07** [comment]
Link to the public vote. https://strawpoll.com/435566r
The winner is _Boaty McBoatface_

**Comment by TheWhiteCollarPlayers** [comment]
I'm gonna let it run for a bit until we need to have a title for some reason

**Comment by TheWhiteCollarPlayers** [comment]
Per our conversation on Discord, the mod title is "Barstool Games", closing this issue.

**Comment by Scrivener07** [comment]
Ive used the word "classic" a few times in various texts within the mod. How about the mod name of.. 
### Classic Games

**Comment by TheWhiteCollarPlayers** [comment]
I am leaning more towards Barstool Games, only because the name gives an idea of the setting for these games, and the tone of them. I feel like Classic Games could apply to anything really, but classic is a great word to use to describe the game

**Comment by Scrivener07** [comment]
I still like Barstool Games, keep it. Classic Games was kinda just a fleeting thought I decided to stick here.
