### ISSUE TITLE
Cannot re-activate table

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Gambling#12]
After the player first activates the table and is presented with the yes or no option, if they select No, the table cannot be re-activated to bring up the message box again.

**Comment by TheWhiteCollarPlayers** [comment]
Have you taken a look at this bug any more? I looked through the code and I could not pinpoint where the necessary code would go, it might actually be related to the quest in the CK as opposed to the code itself.

**Comment by Scrivener07** [comment]
The bug does not exist on the object branch at this point. I hoping I can finish these core changes and merge it into master soon.

**Comment by TheWhiteCollarPlayers** [comment]
Gotcha, I will wait for you to do that then and test before I look at the CK.

**Comment by TheWhiteCollarPlayers** [comment]
As of my last round of testing, this bug still exists.

**Comment by Scrivener07** [comment]
Can you provide some more details here? I have not be able to reproduce this bug at all. What files are you testing in-game?

**Comment by TheWhiteCollarPlayers** [comment]
Sure, here is my full testing process starting from getting a new build from Git:

- Start by downloading the zip file of `master` from Git 

- Extract the contents of `Data` to a folder on my desktop 

- Copy all of those files, except the .esp over to my Fallout 4 Data folder, replacing all files in the destination when the window pops up 

- Download the other .esp you sent via Discord a while back, and place it in my Fallout 4 Data folder 

- Activate the .esp and load the game, using the quickstart save 

- Run over to the table, press 'E' to activate it 

- When the box pops up asking me if I would like to play, I press 'No' 

- The box closes and when I try to press 'E' on the table again, nothing happens, the box doesn't pop up, nothing. 


So I guess one possibility is the old ESP I was using?

**Comment by Scrivener07** [comment]
An old esp is my first thought. I'm almost certain (short of actually checking) that esp is too old to work. I recently changed a bunch of properties when I merged `Players` component into the main `Game` class, see #21.

Thanks for the nice step by step too. Im going to make your comment the bones for [CONTRIBUTING.md](https://github.com/Scrivener07/FO4_Gambling/blob/master/CONTRIBUTING.md). Hopefully that will fast track folks into getting everything setup for dev and testing correctly.

**Comment by TheWhiteCollarPlayers** [comment]
Ok gotcha, and ya good idea about using it for contributing.

**Comment by Scrivener07** [comment]
Does this issue still exist for you?

**Comment by TheWhiteCollarPlayers** [comment]
Nope! Bug fixed! Gonna close this issue!
