### ISSUE TITLE
A requirement to enter the casino is imposed on the player.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Gambling#14]
An introductory quest that imposes a requirement in order to gain entrance to the casino.
- [ ] Entrance (A) Minimum caps requirement in order to gain entrance.
- [ ] Entrance (B) Attribute requirement in order to gain entrance.
- [ ] Entrance (C) Mission requirement in order to gain entrance.

**Comment by TheWhiteCollarPlayers** [comment]
As this is not necessary for our first playable release, I do not plan to work on it until we are at a comfortable spot for our Alpha build. However, I have a good foundation started for when we reach that point.

**Comment by Scrivener07** [comment]
Closing, see issue #1.
