### ISSUE TITLE
Table vs NPC

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [Scrivener07/FO4_Gambling#28]
Should we place tables around the world or an NPC to start the blackjack game? My personal vote is NPC for the following reasons: 
1) Saves space when placing him in various locations, which means more areas can allow the player to gamble.
2) Allows for easy addition of new games, just a new dialogue option.
3) Closely resembles the method used by the Skyrim mod "tavern games"
4) Can easily vary the appearance of the dealer to match the environment that he/she is placed in. 

There might be more pros and there might be cons I am not considering but I really think this is a great option, please feel free to disagree and challenge me on it, but I want feedback before we start working on adding the game to worldspaces.

**Comment by Scrivener07** [comment]
Yea, I think its a great idea too. Go ahead and dive into it! Let me know if anything about [Actions:Play](https://github.com/Scrivener07/FO4_Gambling/blob/ec3f2ca2433b74350e024b470ff560feee2c9688/Data/Scripts/Source/FO4_Gambling/Gambling/Blackjack/Actions/Play.psc) script needs to be changed to support starting a game through dialogue.

**Comment by TheWhiteCollarPlayers** [comment]
One thing to change, can you remove the debug box that asks you to confirm playing the game?

**Comment by Scrivener07** [comment]
Oh yea, I see. You probably want to prompt those questions within the NPC dialogue. I will have to take a little time to think that through but I will surely remove it one way or another so you can do your thing.

**Comment by TheWhiteCollarPlayers** [comment]
Should be along the lines of removing the condition that checks for yes or no and just placing the playgame function right there instead of the condition check being there

**Comment by Scrivener07** [comment]
Well for something quick n dirty that would work. I dont want to completely remove the message though in the case that the play action was not via dialogue. I still want to be able to support other methods of game activation like and inventory item or in game activator.

**Comment by TheWhiteCollarPlayers** [comment]
Possibly another quick and dirty route but what about basically copying everything and putting it into "PlayBlackJack_Dialogue" script which doesn't have the message box and is just the one we use to attach for dialogue execution?

**Comment by Scrivener07** [comment]
Good idea, I will give that a shot. Do you have a dialogue script ready to call Blackjack.Play() yet?

**Comment by TheWhiteCollarPlayers** [comment]
Like a script I have written? No, what I'm hoping is that you write that "Play via Dialogue" script and then when it is ready to go and you have merged it into the master files on Git, I will update my files and then attach that new script on the back end of the dialogue I create

**Comment by TheWhiteCollarPlayers** [comment]
On dialogue there is literally a "run script on end" option that I will put that script into

**Comment by Scrivener07** [comment]
Okay. I will make something that works in that case.

**Comment by Scrivener07** [comment]
With commit ec3f2ca, I hope you can now use the existing actions:play script in dialogue.

**Comment by TheWhiteCollarPlayers** [comment]
I'm going to close this issue since we now have the functioning dialogue script as well as functioning tables so this is no longer an issue, we simply implement however we want wherever we want!

**Comment by Scrivener07** [comment]
Yaay!
