### ISSUE TITLE
Card positioning does not handle rotation

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Gambling#4]
The black jack [Cards](https://github.com/Scrivener07/FO4_Gambling/blob/a52625a96fe3ff85416570359b4f787d7e335b2e/Data/Scripts/Source/FO4_Gambling/Gambling/BlackJack/Cards.psc#L31) do not handle the roation of a target table marker.

**Comment by TheWhiteCollarPlayers** [comment]
With our decision to approach the bound method, this issue becomes void. We can reopen another one if we choose to approach an unbound method, but for now I am closing this.

**Comment by Scrivener07** [comment]
Good call though may aswell repon this existing one instead of creating a new one if it becomes relevant again.

Yay, first issue closed!
