### ISSUE TITLE
How to handle blackjack game mode?

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Gambling#5]
# How do we present the game to the player and what should their experience be like?
Lets try to make a healthy case for and against each of these. Please add your thoughts or concerns and feel free to edit this post with more details as we discuss each of them.

## Bound
Only one game table exists in an inaccessible cell. When entering game mode, the player is teleported to this games location. The players controls will be limited and the camera directed by relevant game actions, most likely a top down view of the game.

**Summation** Bound offers a satisfactory gambling experience for a reasonable development cost.

**Positives**
* [Tavern Games of Skyrim](http://www.nexusmods.com/skyrim/mods/68553) has proven this method to work well.
* Bound allows for easy implementation and expandability.
* Very clear and understandable requirements for player interaction. 

**Negatives**
* Player cannot observe a game in progress unless they are directly participating.
* The gambling cell may not accurately reflect the environment of the players location.
* A loading screen may appear briefly.

## Unbound
Multiple hand placed game tables exist in the world. The player enters game mode by activating the game like you would furniture. The player is free to look around and interact with objects and competitors as the game carries onward.

**Summation** Unbound offers an unparalleled immersive gambling experience at a substantial development cost.

**Positives**
* Player may observe and interact with competitors.
* Preserves the environment of the players location.
* Autonomous gameplay. Player may observe a game in progress participated only by competitor AI.

**Negatives**
* The technical development cost is very high.
* Complicated player experience. Interacting with and playing a game may require more feedback to the player due to its unguided nature.

**Comment by TheWhiteCollarPlayers** [comment]
**Argument for Bound**
Implementing this design would likely be much easier as most of the technical updates and changes happen in a separate, controlled, environment. Meaning that creating other casinos around the commonwealth would be much easier to accomplish. Adding or updating the games would also be much easier as it just becomes a matter of making change to code dealing with only one cell, even though there might be several casinos scattered about. We can preserve the atmosphere of the original casino by using ambient sound effects and different textures for the standard blackjack table used in the controlled cell. In summation: Bound allows for easy implementation and expandability.

**Comment by TheWhiteCollarPlayers** [comment]
**Argument for Unbound**
This method preserves immersion and the environment of the casino. It allows the player to look at his NPC competitors in real time while cards are dealt in front of them. By implementing control of the game functions (hitting or standing) through dialogue with the dealer, even more immersion and realism is attained and makes passing time in the casino much more realistic and entertaining. In summation: Unbound allows for an un-paralleled immersive gambling experience.

**Comment by TheWhiteCollarPlayers** [comment]
**My Personal Opinion On Which Method To Use**
I would prefer to use Bound for several reasons, chief of which is expandability and implementation.
I believe that the game mechanics will be much smoother and simpler, which for the player will outweigh the loss of immersion and waiting for a short loading screen. Looking ahead to the future, this is also a better option, we can implement more casinos much more easily and new games fairly quickly as well. I also didn't mind the way that FNV handled the gambling which would be very similar to this method. Using custom ambient noises and textures for the tables, we can make the game visually and acoustically appealing to easily make up for the minor loss in immersion. I would like to ensure that time passes in the control cell similar to how it would if the player was just playing in the original cell (which I am currently testing). With custom effects and smooth player controls, I think Bound would be a fantastic option for this stage of the mod, if we come across a new way to implement the game in the original cell that makes it much much easier then we can revisit the Unbound option at that time, for now I would argue that we steer towards the Bound option.

**Comment by Scrivener07** [comment]
I agree with you on pursuing a bound experience too. An unbound experience is what I was aiming for in my initial efforts and while possible I think it would be a detriment to our first milestone at this time. All efforts towards an unbound experience at this point are preserved on another branch called `Experimental-Factory`. We can revisit it again at some point in the future if we decide to change direction again. 

I have found a very nice role model called [Tavern Games of Skyrim](http://www.nexusmods.com/skyrim/mods/68553) for us to follow. I feel this mod conforms to our definition of a "bound" experience. Do you also agree that this is what we should attempt to replicate?

**Comment by TheWhiteCollarPlayers** [comment]
I completely agree that we should follow that mod's general format. I might install Skyrim and download the mod to play around with it and poke at it in the CK to get some ideas. I would ideally like to use less of the debug message boxes, but with a Bound approach that might be pretty difficult to accomplish. But I do think that for a first playable build especially that mod is an ideal format to follow, so yes I agree. What do you think of reaching out to the mod author to see if he/she has any words of wisdom?

**Comment by Scrivener07** [comment]
Installing skyrim to play tavern games is a great idea, it has been awhile since I have myself. I totally agree about the message boxes, yuck! At some point I can add in some new HUD widgets to display certain game details like the phase the game is currently in, the cards in your hand, your wager, and others things we would like to communicate to the player.

Sagittarius22 is popular so Im sure his inbox is smashed all the time. I would definitely craft a thoughtful and detailed message before reaching out to him. Also include video of progress so he knows we are serious about this project. With that, yea, reach out to him and see if he has any helpful words for us.

**Comment by Scrivener07** [comment]
Created a follow up issue #11 for a bound presentation.

**Comment by TheWhiteCollarPlayers** [comment]
Should we close this? I think Bound would be or best way to approach it, especially since that is how "Tavern Games" handled it

**Comment by Scrivener07** [comment]
Yup. We are fully committed to the bound style now. Closing this question.
