### ISSUE TITLE
Game does not deallocate properly

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Gambling#8]
As shown in this [video](https://youtu.be/6fm8QedoMTg), a black jack game does not clean up and deallocate itself properly after a previous game has been completed.

**Comment by TheWhiteCollarPlayers** [comment]
I see what you mean about de-allocating. Would it be possible to insert some code after the player indicates that they want to play again but before everything else to reset the cards? (would also be cool to see the cards fly back to the deck) Or is there a way to force a cell reset which would reset the game?

**Comment by Scrivener07** [comment]
The game now deallocates properly with commit 	b2e2afc.
